---
- name: Install and configure app components manually per host
  hosts: all
  become: yes
  tasks:
    # Install Docker and prerequisites
    - name: Update apt cache
      apt:
        update_cache: yes
    - name: Install Docker
      apt:
        name: docker.io
        state: present
    - name: Start and enable Docker service
      service:
        name: docker
        state: started
        enabled: true
    - name: Add ubuntu user to docker group (no sudo needed)
      user:
        name: ubuntu
        groups: docker
        append: yes
############################################################
# FRONTEND INSTANCE — vote + result
############################################################
- name: Deploy frontend containers (vote + result)
  hosts: frontend-instance-1
  become: yes
  tasks:
    - name: Pull vote image
      community.docker.docker_image:
        name: "chojiu/vote-project-1"
        tag: latest
        source: pull
    - name: Run vote container
      community.docker.docker_container:
        name: vote
        image: "chojiu/vote-project-1:latest"
        ports:
          - "80:80"
        env:
          REDIS_HOST: "10.0.2.68" # IP of Redis
          REDIS_PORT: "6379"
        state: started
        restart_policy: always
    - name: Pull result image
      community.docker.docker_image:
        name: "chojiu/result-project-1"
        tag: latest
        source: pull
    - name: Run result container
      community.docker.docker_container:
        name: result
        image: "chojiu/result-project-1:latest"
        ports:
          - "81:80"
        env:
          PG_HOST: "10.0.3.37" # IP of Postgres
          PG_USER: "postgres"
          PG_PASSWORD: "postgres"
          PG_NAME: "postgres"
          PG_PORT: "5432"
        state: started
        restart_policy: always
############################################################
# BACKEND INSTANCE — redis + worker (shared private network)
############################################################
- name: Deploy backend containers (redis + worker)
  hosts: backend-instance-1
  become: yes
  tasks:
    - name: Create internal Docker network for backend
      docker_network:
        name: backend_network
        driver: bridge
        state: present
    - name: Pull redis image
      community.docker.docker_image:
        name: redis
        source: pull
    - name: Run redis container
      community.docker.docker_container:
        name: redis
        image: redis
        ports:
          - "6379:6379"
        networks:
          - name: backend_network
        state: started
        restart_policy: always
    - name: Pull worker image
      community.docker.docker_image:
        name: "chojiu/worker-project-1"
        tag: latest
        source: pull
    - name: Run worker container
      community.docker.docker_container:
        name: worker
        image: "chojiu/worker-project-1:latest"
        env:
          REDIS_HOST: "redis" # hostname because of shared network
          DB_HOST: "10.0.3.37"
          DB_USER: "postgres"
          DB_PASSWORD: "postgres"
          DB_NAME: "postgres"
        networks:
          - name: backend_network
        state: started
        restart_policy: always
############################################################
# DB INSTANCE — Postgres
############################################################
- name: Deploy db container (PostgreSQL)
  hosts: db-instance-1
  become: yes
  tasks:
    - name: Pull postgres image
      community.docker.docker_image:
        name: postgres
        tag: latest
        source: pull
    - name: Run postgres container
      community.docker.docker_container:
        name: postgres
        image: postgres:latest
        ports:
          - "5432:5432"
        env:
          POSTGRES_USER: "postgres"
          POSTGRES_PASSWORD: "postgres"
          POSTGRES_DB: "postgres"
        state: started
        restart_policy: always
